version: '3.4'
services:
  client:
    image: alonkop/findmesongs-frontend:latest
    networks:
      - findmesongs_network
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=dev
      - PORT=5000
      - HOST=0.0.0.0
  server:
    image: alonkop/findmesongs-backend:latest
    networks:
      - findmesongs_network
    command: uvicorn src.main:app --host 0.0.0.0 --port 4000
    ports:
      - "4000:4000"

networks:
  findmesongs_network:
    external: true